workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.macromaster.app"
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
      - name: Run tests
        script: |
          ./gradlew test
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  android-app-debug:
    name: Android App Debug
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.macromaster.app"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
      - name: Run tests
        script: |
          ./gradlew testDebugUnitTest
    artifacts:
      - app/build/outputs/**/*.apk